export const USER_MESSAGE = {
  VALIDATION_ERROR: 'Validation error',
  EMAIL_ALREADY_EXIST: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_STRING: 'Password must be a string',
  PASSWORD_LENGTH: 'Password must be from 6 to 50 characters',
  PASSWORD_STRONG:
    'Password must be 6-50 characters long, at least one lowercase letter, one uppercase letter, one number, one symbol',
  CONFIRM_PASSWORD_REQUIRED: 'Confirm Password must be required',
  CONFIRM_PASSWORD_MUST_BE_STRING: 'Confirm Password must be a string',
  CONFIRM_PASSWORD_MATCHED: 'Confirm Password does not matched',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_STRING: 'Name must be a string',
  NAME_LENGTH: 'Name length must be from 1 to 100 characters',
  USER_NOT_FOUND: 'Email or password is not correct',
  LOGIN_SUCCESSFUL: 'Login success',
  REGISTER_SUCCESSFUL: 'Register success',
  EMPTY_ACCESS_TOKEN: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  USED_REFRESH_TOKEN_OR_NOT_EXIST: 'Used refresh token or not exist',
  LOGOUT_SUCCESS: 'Logout success',
  ACCESS_TOKEN_IS_INVALID: 'Access token is invalid',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verification token is required',
  EMAIL_VERIFIED: 'Email verification token is verified already',
  EMAIL_VERIFIED_SUCCESS: 'Email verified successfully',
  EMAIL_VERIFY_TOKEN_IS_INVALID: 'Email verification token is invalid'
}
